# Copyright © 2022 Durudex
#
# This file is part of Durudex: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# Durudex is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Durudex. If not, see <https://www.gnu.org/licenses/>.

version: '3.8'

services:
  app:
    image: durudex-code-service
    container_name: durudex-code-service
    build:
      context: .
      dockerfile: Dockerfile
    hostname: code.service.durudex.local
    ports:
      - 8003:8003
    depends_on:
      - redis
    volumes:
      - ./.bin/:/root/
      - ./certs/:/root/certs/
      - ./configs/:/root/configs/
    env_file:
      - .env
    networks:
      - durudex-backend
      - durudex-database

  redis:
    image: redis:alpine
    container_name: auth-redis
    command: redis-server
    hostname: auth.redis.durudex.local
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - durudex-auth:/data
    networks:
      - durudex-database

volumes:
  durudex-auth:
    name: durudex-auth

networks:
  durudex-backend:
    driver: bridge
    name: durudex-backend
  durudex-database:
    driver: bridge
    name: durudex-database
